apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tm4q
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0058-tenant/tkrw-pr712-0075-0058-app/devfile-sample-tm4q@sha256:00e80a01da4c35fec8e65a70af6b34eb54cda765bef3b8479e5889d8c4cd779b
        name: my-nodejs
        resources: {}
status: {}
