apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-tm4q
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-tm4q
    app.kubernetes.io/part-of: tkrw-pr712-0075-0058-app
  name: devfile-sample-tm4q
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-tm4q
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-tm4q
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0058-tenant/tkrw-pr712-0075-0058-app/devfile-sample-tm4q@sha256:00e80a01da4c35fec8e65a70af6b34eb54cda765bef3b8479e5889d8c4cd779b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
